language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
script:
- npm run build
- "[[ -z $TRAVIS_TAG ]] || mvn clean deploy --settings settings.xml"
env:
  global:
  - secure: FmTTvMEbZ16/bo8+NPa4aiokIGzbelYwas4XhTkJHi2KR/JpZ1X+pA/pLx0rkZtt5Il+OI+OAJEsGRj8hMSdUxhOCibSlYHnnDAh9Kfz/qio80/qRZO1d4n+gBZ2EQ2VIASvSYWGG1B1Qq0aUpQ7Y8HGMp3exfMqs+PvRYpGb4mm4ohZeI9lslQEbFyQSofxZ4Pi+7Mu6TtFiR+hz3ESD5uA5c/8c2/YM9Y4Y0XzfiLuHXh/1WVYKnbDi7rfUfygen9pWx4yVyXRM7bmv3wcCUuN4DK8hAbZRsDQBcOJNWwxs9hGcBRZpb0CanCl9hzy5K9kXj61SICp113RAL8rUlUAjrhwHNLNSfYu5HGS8Vb5e8GJEn24PyHLB3EhWlKgPXsFo4E6vWkpnc+gCmEIe2FZna/k/9VmgkMqpmUWkaFC3Zh3Hnl89Onv9mxwJmp3JUXxmoPhXbrsJqCrGdPQSDEALESSj4BgBFwDxWIm84uiqww+pLYMrxbD79H57jWcHWo9gLP8NDE8pxBbc7LXrGLHb1z57Er++ZJ2Y7DRHNtD2XLCEsr2aBIuMtNNB4iLQKLpfWbHaWyKu5dXQEwACkO3rnOJxY6DifRxnGCW59xiJ0amRqp334mVBeXYSe+1XXP+ZCn7axkluxFXV8P27HvuvceMyFK7Ox2eCHWOJNo=
  - secure: XBvAetrs25xFreYvtJ6VEXfqNJRxhkem7Zc0rPBlP7g0rLAzLieQ04JY/AcAz5Uh3FWCcIVJdEbfJnj2StDYIRYnjy3s1Tx2Db/bzOvtpmQZ7IGntqYvMhdF4dSsRcfMpdNhSgBbPx7wvAn4y4k1fdrjdCdnssfMq8MQ8aIT+7b2qQgfWbbfQ6WX5DYc7/j8GqBAS+aHSIkPzldCb2CrkGGllzj8I+OxvZnQR/Ebityl7wZY1Uo1yL8D2v381fqEFgrWdcroE8qyDEtMkhx3RupXHia+4RClbaoqolgBgdGHkL/c57fvkzvJMofnemqs4v1HuJ4VcK+b67k8gG0KDvbHzE8W86PcNSrPYI+vuWFYw+J5qnDt2+6W1326OVRxwIMUvfHRKcH8BnETcIWcNdGo7oKTw/Pf6kO+rbHKi6c0rYQHlVt8w89X8ZoEbeakaCi+FuvwDOfYIZkcVoj17MBDXWLJJS0hq6CTX29jmBNrNrROgH+7jDSm7mZ1yXk2v5c3+814Q/eEVefsvII+/Pzbhtp02G4Lna9kK/gJ8JwQJ15AKn+qSYL3R2q0GnoSGE/EIhCnfOGQtRZaNlZzbGagSSzy9iN1XuvjP7q3B67606vjaIOwQKGDMFpuliPbJLqw6lzFTCQlYv88weDi/rsyhFUzyluPuEpxFQvGRVc=
