language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: deploy/deploy.sh
env:
  global:
  - secure: FmTTvMEbZ16/bo8+NPa4aiokIGzbelYwas4XhTkJHi2KR/JpZ1X+pA/pLx0rkZtt5Il+OI+OAJEsGRj8hMSdUxhOCibSlYHnnDAh9Kfz/qio80/qRZO1d4n+gBZ2EQ2VIASvSYWGG1B1Qq0aUpQ7Y8HGMp3exfMqs+PvRYpGb4mm4ohZeI9lslQEbFyQSofxZ4Pi+7Mu6TtFiR+hz3ESD5uA5c/8c2/YM9Y4Y0XzfiLuHXh/1WVYKnbDi7rfUfygen9pWx4yVyXRM7bmv3wcCUuN4DK8hAbZRsDQBcOJNWwxs9hGcBRZpb0CanCl9hzy5K9kXj61SICp113RAL8rUlUAjrhwHNLNSfYu5HGS8Vb5e8GJEn24PyHLB3EhWlKgPXsFo4E6vWkpnc+gCmEIe2FZna/k/9VmgkMqpmUWkaFC3Zh3Hnl89Onv9mxwJmp3JUXxmoPhXbrsJqCrGdPQSDEALESSj4BgBFwDxWIm84uiqww+pLYMrxbD79H57jWcHWo9gLP8NDE8pxBbc7LXrGLHb1z57Er++ZJ2Y7DRHNtD2XLCEsr2aBIuMtNNB4iLQKLpfWbHaWyKu5dXQEwACkO3rnOJxY6DifRxnGCW59xiJ0amRqp334mVBeXYSe+1XXP+ZCn7axkluxFXV8P27HvuvceMyFK7Ox2eCHWOJNo=
  - secure: XBvAetrs25xFreYvtJ6VEXfqNJRxhkem7Zc0rPBlP7g0rLAzLieQ04JY/AcAz5Uh3FWCcIVJdEbfJnj2StDYIRYnjy3s1Tx2Db/bzOvtpmQZ7IGntqYvMhdF4dSsRcfMpdNhSgBbPx7wvAn4y4k1fdrjdCdnssfMq8MQ8aIT+7b2qQgfWbbfQ6WX5DYc7/j8GqBAS+aHSIkPzldCb2CrkGGllzj8I+OxvZnQR/Ebityl7wZY1Uo1yL8D2v381fqEFgrWdcroE8qyDEtMkhx3RupXHia+4RClbaoqolgBgdGHkL/c57fvkzvJMofnemqs4v1HuJ4VcK+b67k8gG0KDvbHzE8W86PcNSrPYI+vuWFYw+J5qnDt2+6W1326OVRxwIMUvfHRKcH8BnETcIWcNdGo7oKTw/Pf6kO+rbHKi6c0rYQHlVt8w89X8ZoEbeakaCi+FuvwDOfYIZkcVoj17MBDXWLJJS0hq6CTX29jmBNrNrROgH+7jDSm7mZ1yXk2v5c3+814Q/eEVefsvII+/Pzbhtp02G4Lna9kK/gJ8JwQJ15AKn+qSYL3R2q0GnoSGE/EIhCnfOGQtRZaNlZzbGagSSzy9iN1XuvjP7q3B67606vjaIOwQKGDMFpuliPbJLqw6lzFTCQlYv88weDi/rsyhFUzyluPuEpxFQvGRVc=
notifications:
  slack:
    rooms:
      secure: WG4hb5RIO5J/XImHl0VNF/vSPsxpNBVrIlyz3qHR/4C1Yy327b3syfqck7lmHkFqNHVjc1NnxGCBLM2DCs9fZPNBYyJebvFzzJQf/AqHbOXae9ODxByPs4LbWGHbOXiZ2o6fDNa6KozeYPD9M8cK5V5uY8sR+Iqx1AUb4QpdOwSsEnNhsQqAk+RLjbOOUQqtV+q/h+E/mLf6PqUsm17gYwf3+u298dF2B72e8ThHjM11CJNPJaugGwg1zKUQs7UmhGXrUgUJCk/FlhrSoYGIOoDxPU4Z3dPLTs/w7xOCiFi2/q1pgClWnFaQLDQhHC5ckOYAazKd/9yphHVPMXIAJ5BCYyVXwY5MDFnOgyWKgmBz/fDbUsp/4FjwA39HCcsfI+KS55HaL9fsssKxnEphHqRbDg+wcnh7UFl+QKvba7OprlR5yu3EDbs4YQ7SztxSbOEC+iFzm4KOGyfIV0dDBlkFjKtDBjx43IURi1Ma6qStd75alUAUt9Srj/oNzINf7sTCY6TbIJ7jnY1qqHed4LWJmanLXUSR4qoZT6GC1BNmHtBQ2H4miaZ0uq4Vnoqh0hBAUMLRJKkStLhzP87PhnNscdHzXzT0VsgcU1OSCGmwxTX13YU7cqX5xQZ/MHCB//yqme0ezuI5TaQdXaCkp2KYTps9aeMJv+RId945hu4=
    on_success: change
    on_failure: always
